tal1 = int(input("Mata in ett tal"))
tal2 = int(input("Mata in ett till tal"))
print(f"Summan av {tal1} och {tal2} är {tal1+tal2}")
print(f"Differensen av {tal1} och {tal2} är {tal1-tal2}")
print(f"Medelvärde av {tal1} och {tal2} är {(tal1+tal2)/2}")
